# Generated by Django 5.0.6 on 2025-08-21 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='VAT % e.g. 13 for 13%', max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='kids.kid')),
            ],
            options={
                'ordering': ['-year', '-month', 'kid__name'],
                'unique_together': {('kid', 'month', 'year')},
            },
        ),
    ]
