# Generated by Django 5.0.6 on 2025-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutsection_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='title',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='order',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(default='Hello All'),
        ),
    ]
