# Generated by Django 5.0.6 on 2025-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.TextField(default='Welcome to IRIS FAMILY HOSTEL', max_length=255),
        ),
    ]
