# Generated by Django 5.0.6 on 2025-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_herosection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About IRIS FAMILY HOSTEL', max_length=255)),
                ('content', models.TextField(default='Hello All')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Tour_images/')),
            ],
        ),
    ]
