# Generated by Django 5.0.6 on 2025-08-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_toursection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toursection',
            old_name='heading',
            new_name='head',
        ),
    ]
