# Generated by Django 5.0.6 on 2025-08-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_toursection_image_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_images/'),
        ),
    ]
