# Generated by Django 5.0.6 on 2025-10-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_expection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Position or role of the team member, e.g., House Warden', max_length=100)),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('description', models.TextField(help_text='Short bio or introduction for the team member')),
                ('is_active', models.BooleanField(default=True, help_text='If True, will be displayed on the About page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on the page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
