# Generated by Django 5.0.6 on 2025-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('guardian_contact', models.CharField(blank=True, max_length=50)),
                ('admission_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kids_photos/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
